env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - id: gokeyless-darwin
    binary: gokeyless
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/gokeyless
    flags:
      - -tags=pkcs11
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: gokeyless-linux
    binary: gokeyless
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/gokeyless
    flags:
      - -tags=pkcs11
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -linkmode external -extldflags "-static"
archives:
  - format: binary
release:
  github:
    owner: cloudflare
    name: gokeyless
  prerelease: auto
changelog:
  sort: asc
nfpms:
  - id: keyless-nfpm
    package_name: gokeyless
    file_name_template: "gokeyless_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/cloudflare/gokeyless
    maintainer: SSL Cloudflare <securityengineering@cloudflare.com>
    description: Go implementation of keyless protocol
    license: BSD 3-Clause
    formats:
      - deb
      - rpm

