env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - id: gokeyless-darwin
    binary: gokeyless
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/gokeyless
    flags:
      - -tags=pkcs11,netgo
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: gokeyless-linux
    binary: gokeyless
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/gokeyless
    flags:
      - -tags=pkcs11,netgo
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -linkmode external -extldflags "-static"
archives:
  - format: binary
release:
  github:
    owner: cloudflare
    name: gokeyless
  prerelease: auto
changelog:
  sort: asc
nfpms:
  - id: keyless-nfpm
    package_name: gokeyless
    file_name_template: "gokeyless_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/cloudflare/gokeyless
    maintainer: SSL Cloudflare <security-engineering@cloudflare.com>
    description: Go implementation of keyless protocol
    license: Cloudflare
    formats:
      - deb
      - rpm
    overrides:
      deb:
        scripts:
          preinstall: pkg/debian/before-install.sh
          postinstall: pkg/debian/after-install.sh
          preremove: pkg/debian/before-remove.sh
      rpm:
        scripts:
          preinstall: pkg/centos/before-install.sh
          postinstall: pkg/centos/after-install.sh
          preremove: pkg/centos/before-remove.sh
    contents:
      - src: pkg/gokeyless.service
        dst: /lib/systemd/system/gokeyless.service
        file_info:
          mode: 0644
      - src: pkg/gokeyless.sysv
        dst: /etc/init.d/gokeyless
        file_info:
          mode: 0755
        type: config
      - src: pkg/keyless_cacert.pem
        dst: /etc/keyless/keyless_cacert.pem
        file_info:
          mode: 0644
        type: config
      - src: pkg/gokeyless.yaml
        dst: /etc/keyless/gokeyless.yaml
        file_info:
          mode: 0600
        type: "config|noreplace"
