// Code generated by "stringer -type=Tag,Op -output=protocol_string.go"; DO NOT EDIT

package gokeyless

import "fmt"

const (
	_Tag_name_0 = "TagCertificateDigestTagServerNameTagClientIPTagSubjectKeyIdentifierTagServerIPTagSigAlgs"
	_Tag_name_1 = "TagOpcodeTagPayload"
	_Tag_name_2 = "TagPadding"
)

var (
	_Tag_index_0 = [...]uint8{0, 20, 33, 44, 67, 78, 88}
	_Tag_index_1 = [...]uint8{0, 9, 19}
	_Tag_index_2 = [...]uint8{0, 10}
)

func (i Tag) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Tag_name_0[_Tag_index_0[i]:_Tag_index_0[i+1]]
	case 17 <= i && i <= 18:
		i -= 17
		return _Tag_name_1[_Tag_index_1[i]:_Tag_index_1[i+1]]
	case i == 32:
		return _Tag_name_2
	default:
		return fmt.Sprintf("Tag(%d)", i)
	}
}

const (
	_Op_name_0 = "OpRSADecryptOpRSASignMD5SHA1OpRSASignSHA1OpRSASignSHA224OpRSASignSHA256OpRSASignSHA384OpRSASignSHA512"
	_Op_name_1 = "OpECDSASignMD5SHA1OpECDSASignSHA1OpECDSASignSHA224OpECDSASignSHA256OpECDSASignSHA384OpECDSASignSHA512"
	_Op_name_2 = "OpCertificateRequest"
	_Op_name_3 = "OpRSAPSSSignSHA256OpRSAPSSSignSHA384OpRSAPSSSignSHA512"
	_Op_name_4 = "OpResponseOpPingOpPongOpActivate"
	_Op_name_5 = "OpError"
)

var (
	_Op_index_0 = [...]uint8{0, 12, 28, 41, 56, 71, 86, 101}
	_Op_index_1 = [...]uint8{0, 18, 33, 50, 67, 84, 101}
	_Op_index_2 = [...]uint8{0, 20}
	_Op_index_3 = [...]uint8{0, 18, 36, 54}
	_Op_index_4 = [...]uint8{0, 10, 16, 22, 32}
	_Op_index_5 = [...]uint8{0, 7}
)

func (i Op) String() string {
	switch {
	case 1 <= i && i <= 7:
		i -= 1
		return _Op_name_0[_Op_index_0[i]:_Op_index_0[i+1]]
	case 18 <= i && i <= 23:
		i -= 18
		return _Op_name_1[_Op_index_1[i]:_Op_index_1[i+1]]
	case i == 32:
		return _Op_name_2
	case 53 <= i && i <= 55:
		i -= 53
		return _Op_name_3[_Op_index_3[i]:_Op_index_3[i+1]]
	case 240 <= i && i <= 243:
		i -= 240
		return _Op_name_4[_Op_index_4[i]:_Op_index_4[i+1]]
	case i == 255:
		return _Op_name_5
	default:
		return fmt.Sprintf("Op(%d)", i)
	}
}
