name: goreleaser

on:
  push:
  workflow_dispatch:
    # tags:
    #   - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Run Release
        run: make release-github
        # uses: goreleaser/goreleaser-action@v2
        # with:
        #   args: release --rm-dist
        env:
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
