name: Image snapshots

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y softhsm2
      - run: sudo cp -r tests/testdata/tokens/* /var/lib/softhsm/tokens
      - run: make snapshot
      # latest snapshot looks like dist/gokeyless_0.0.0-SNAPSHOT-99d510e_linux_amd64.deb
      - run: sudo dpkg -i dist/*.deb
      - run: sudo gokeyless --version
      - run: gokeyless --keystore-debug -c tests/testdata/keystoredebug-dir.yaml
      # test for  #324
      - run: sudo ./dist/gokeyless-linux_linux_amd64_v1/gokeyless --keystore-debug -c tests/testdata/keystoredebug-softhsm.yaml
      - run: sudo gokeyless --keystore-debug -c tests/testdata/keystoredebug-softhsm.yaml
      - name: ensure systemd service can start
        run: sudo systemctl start gokeyless
      - name: ensure keyless user exists
        run: sudo grep "keyless" /etc/passwd
      - run: sudo dpkg -r gokeyless
      - name: ensure keyless user was removed after uninstall
        run: sudo grep -v "keyless" /etc/passwd
      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/*
